spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bestmatchedrestaurants
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    io.challenge.bestmatched: DEBUG